---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: beta-app
spec:
  type: ClusterIP
  ports:
    - port: 9192
      targetPort: 9192
  selector:
    app.kubernetes.io/name: api-gateway